(* ::Package:: *)

(* ::Input:: *)
(*(*Load AmpRed*)*)
(*<<AmpRed`;*)
(*(*Define kinematics*)*)
(*(*(IJ) channel*)*)
(*SP[vI,vJ]=-(1/2)(aIJ+1/aIJ);*)
(*SP[vI,vI]=1;*)
(*SP[vJ,vJ]=1;*)
(*(*(JK) channel*)*)
(*SP[vK,vJ]=-(1/2)(aJK+1/aJK)/.{aIK->lam/yIJk,aJK->lam yIJk};*)
(*SP[vK,vK]=1;*)
(*SP[vJ,vJ]=1;*)
(*(*(IK) channel*)*)
(*SP[vI,vK]=-(1/2)(aIK+1/aIK)/.{aIK->lam/yIJk,aJK->lam yIJk};*)
(*SP[vI,vI]=1;*)
(*SP[vK,vK]=1;*)
(*(*Define the scalar integrals*)*)
(*(*Only one timelike line is regularised*)*)
(*intI=Expand[Simplify[ToFeynmanInt[(*NumI**)1/(SP[q1+q3,vJ]-1+ie)*1/(SP[q2-q3,vK]+ie)*1/(-SP[q1+q2,vI]+ie)*1/(-SP[q1,vI]+ie)*1/SP[q1,q1]*1/SP[q2,q2]*1/SP[q3,q3]*1/SP[q1+q3,q1+q3]*1/SP[q2-q3,q2-q3],{q1,q2,q3}]]]/.ie->0;*)
(*(*Only one timelike line is regularised*)*)
(*intJ=Expand[Simplify[ToFeynmanInt[(*NumJ**)1/(SP[q1+q3,vI]-1+ie)*1/(SP[q2-q3,vK]+ie)*1/(-SP[q1+q2,vJ]+ie)*1/(-SP[q1,vJ]+ie)*1/SP[q1,q1]*1/SP[q2,q2]*1/SP[q3,q3]*1/SP[q1+q3,q1+q3]*1/SP[q2-q3,q2-q3],{q1,q2,q3}]]]/.ie->0;*)
(*(*Only the timelike line with one attachment is regularised*)*)
(*intK=Expand[Simplify[ToFeynmanInt[(*NumK**)1/(SP[q1+q3,vI]-1+ie)*1/(SP[q2-q3,vJ]-1+ie)*1/(-SP[q1+q2,vK]+ie)*1/(-SP[q1,vK]+ie)*1/SP[q1,q1]*1/SP[q2,q2]*1/SP[q3,q3]*1/SP[q1+q3,q1+q3]*1/SP[q2-q3,q2-q3],{q1,q2,q3}]]]/.ie->0;*)
(*(*Parametrize the integrals using Feynman parametrization*)*)
(*intIp=AlphaParametrize[intI];*)
(*intJp=AlphaParametrize[intJ];*)
(*intKp=AlphaParametrize[intK];*)
(*(*Print some info on the 3 parametrized integrals*)*)
(*(*Two gluons on I*)*)
(*Cases2[intIp,AlphaInt[__]]*)
(*AlphaIntExplicit[%]*)
(*AlphaInfo[1,"P"]*)
(*AlphaInfo[1,"F"]*)
(*(*Two gluons on J*)*)
(*Cases2[intJp,AlphaInt[__]]*)
(*AlphaIntExplicit[%]*)
(*AlphaInfo[2,"P"]*)
(*AlphaInfo[2,"F"]*)
(*(*Two gluons on K*)*)
(*Cases2[intKp,AlphaInt[__]]*)
(*AlphaIntExplicit[%]*)
(*AlphaInfo[3,"P"]*)
(*AlphaInfo[3,"F"]*)
(*(*Find the regions*)*)
(*(*I*)*)
(*Cases2[intIp,AlphaInt[__]]*)
(*Export["regionsI.txt", AlphaRegions[%[[1]],{{lam,1}}]]*)
(*Length[%]*)
(*(*J*)*)
(*Cases2[intJp,AlphaInt[__]]*)
(*Export["regionsJ.txt",AlphaRegions[%[[1]],{{lam,1}}]]*)
(*Length[%]*)
(*(*K*)*)
(*Cases2[intKp,AlphaInt[__]]*)
(*Export["regionsK.txt",AlphaRegions[%[[1]],{{lam,1}}]]*)
(*Length[%]*)
